on: [push]
jobs:
  test:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go install github.com/tc-hib/go-winres@latest
      - run: go mod download
      - run: go-winres make
      - run: GOOS=windows GOARCH=amd64 go build -ldflags -H=windowsgui -o wake.exe  # Build the executable